[package]
name = "anathema-values"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
debuginfo-level = 1
jemalloc = false

[dependencies]
parking_lot = { workspace = true }
anathema-render = { path = "../anathema-render" }
