[package]
name = "anathema-values"
version = "0.1.0"
edition = "2021"

[features]
default = []
testing = []

[dependencies]
anathema-render = { path = "../anathema-render" }
parking_lot = { workspace = true }
flume = { workspace = true }
integer-hasher = "0.1.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
